NBA_TEAMS = [
  { short_code: 'TOR', code: 'RAPTORS', name: 'Toronto Raptors' },
  { short_code: 'NYK', code: 'KNICKS', name: 'New York Knicks' },
  { short_code: 'BOS', code: 'CELTICS', name: 'Boston Celtics' },
  { short_code: 'NJN', code: 'NETS', name: 'Brooklyn Nets' },
  { short_code: 'PHI', code: 'SIXERS', name: 'Philadelphia 76ers' },
  { short_code: 'LAL', code: 'LAKERS', name: 'Los Angelas Lakers' },
  { short_code: 'LAC', code: 'CLIPPERS', name: 'Los Angelas Clippers' },
  { short_code: 'SAC', code: 'KINGS', name: 'Sacramento Kings' },
  { short_code: 'PHO', code: 'SUNS', name: 'Phoenix Suns' },
  { short_code: 'GSW', code: 'WARRIORS', name: 'Golden State Warriors' },
  { short_code: 'ATL', code: 'HAWKS', name: 'Atlanta Hawks' },
  { short_code: 'MIA', code: 'HEAT', name: 'Miami Heat' },
  { short_code: 'ORL', code: 'MAGIC', name: 'Orlando Magic' },
  { short_code: 'WAS', code: 'WIZARDS', name: 'Washington Wizards' },
  { short_code: 'CHA', code: 'BOBCATS', name: 'Charlotte Bobcats'},
  { short_code: 'NOH', code: 'PELICANS', name: 'New Orleans Pelicans' },
  { short_code: 'SAS', code: 'SPURS', name: 'San Antonio Spurs' },
  { short_code: 'MEM', code: 'GRIZZLIES', name: 'Memphis Grizzlies' },
  { short_code: 'HOU', code: 'ROCKETS', name: 'Houston Rockets' },
  { short_code: 'DAL', code: 'MAVERICKS', name: 'Dallas Mavericks' },
  { short_code: 'OKC', code: 'THUNDER', name: 'Oklahoma City Thunder' },
  { short_code: 'UTA', code: 'JAZZ', name: 'Utah Jazz' },
  { short_code: 'MIN', code: 'TIMBERWOLVES', name: 'Minnesota Timberwolves' },
  { short_code: 'POR', code: 'TRAILBLAZERS', name: 'Portland Trail Blazers' },
  { short_code: 'DEN', code: 'NUGGETS', name: 'Denver Nuggets' },
  { short_code: 'CHI', code: 'BULLS', name: 'Chicago Bulls' },
  { short_code: 'IND', code: 'PACERS', name: 'Indiana Pacers' },
  { short_code: 'CLE', code: 'CAVALIERS', name: 'Cleveland Cavaliers' },
  { short_code: 'DET', code: 'PISTONS', name: 'Detroit Pistons' },
  { short_code: 'MIL', code: 'BUCKS', name: 'Milwaukee Bucks' }
]
